version: '3.8'

services:
  # Dịch vụ Nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - laravel-network

  # Dịch vụ PHP-FPM
  phpfpm:
    build:
      context: ./docker/phpfpm
      dockerfile: Dockerfile
    container_name: phpfpm
    restart: always
    volumes:
      - ./app:/var/www/html
      - ./docker/phpfpm/php.ini:/usr/local/etc/php/php.ini
    networks:
      - laravel-network

  # Dịch vụ MySQL
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel-network

  # Dịch vụ Redis (nếu bạn cần Redis cho cache hoặc session)
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local