<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateUsersAddInfoTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('users_add_info', function (Blueprint $table) {
            $table->integer('id')->primary()->comment("ID");
            $table->integer('users_id')->comment("ユーザーID");
            $table->string('member_id', 9)->comment("会員No");
            $table->string('login_id', 10)->comment("ログインID");
            $table->string('email', 100)->nullable()->comment("メールアドレス");
            $table->string('delivery_suspension', 20)->nullable()->comment("配信停止");
            $table->string('status', 20)->nullable()->comment("ステータス");
            $table->text('remarks')->nullable()->comment("自由Ghi chú");
            $table->string('name1', 10)->nullable()->comment("氏(漢字)");
            $table->string('name2', 10)->nullable()->comment("名(漢字)");
            $table->string('kana1', 15)->nullable()->comment("氏(かな)");
            $table->string('kana2', 15)->nullable()->comment("名(かな)");
            $table->text('family_register')->nullable()->comment("戸籍名・旧姓メモ");
            $table->string('mental_health_worker_registration_number', 20)->nullable()->comment("精神保健福祉士登録番号");
            $table->string('birth_date', 10)->nullable()->comment("生年月日");
            $table->string('sex', 3)->nullable()->comment("性別");
            $table->text('sex_remarks')->nullable()->comment("性別：その他自由記述");
            $table->string('prefectural_chapters', 10)->nullable()->comment("都道府県支部");
            $table->string('membership_type', 50)->nullable()->comment("会員種別・状況");
            $table->string('membership_fee', 20)->nullable()->comment("会費について");
            $table->string('account_transfer_registration_status', 20)->nullable()->comment("口座振替登録状況");
            $table->string('next_scheduled_account_transfer_date', 10)->nullable()->comment("次回口座振替予定日");
            $table->string('send_materials_to', 50)->nullable()->comment("資料送付先");
            $table->string('information_at_the_time_of_mailing', 100)->nullable()->comment("郵送物送付時情報");
            $table->string('role_1', 2)->nullable()->comment("役割（役員・支部長等）-理事");
            $table->string('role_2', 2)->nullable()->comment("役割（役員・支部長等）-常任理事会（正副会長含む）");
            $table->string('role_3', 2)->nullable()->comment("役割（役員・支部長等）-監事");
            $table->string('role_4', 2)->nullable()->comment("役割（役員・支部長等）-相談役");
            $table->string('role_5', 2)->nullable()->comment("役割（役員・支部長等）-名誉会長");
            $table->string('role_6', 2)->nullable()->comment("役割（役員・支部長等）-代議員");
            $table->string('role_7', 2)->nullable()->comment("役割（役員・支部長等）-都道府県支部長");
            $table->string('role_8', 2)->nullable()->comment("役割（役員・支部長等）-都道府県支部事務局長");
            $table->string('role_9', 2)->nullable()->comment("役割（委員会等）-精神医療・権利擁護委員会");
            $table->string('role_10', 2)->nullable()->comment("役割（委員会等）-地域生活支援推進委員会");
            $table->string('role_11', 2)->nullable()->comment("役割（委員会等）-就労・雇用支援の在り方検討委員会");
            $table->string('role_12', 2)->nullable()->comment("役割（委員会等）-組織強化委員会");
            $table->string('role_13', 2)->nullable()->comment("役割（委員会等）-災害支援体制整備・復興支援委員会");
            $table->string('role_14', 2)->nullable()->comment("役割（委員会等）-機関誌編集委員会");
            $table->string('role_15', 2)->nullable()->comment("役割（委員会等）-刑事司法精神保健福祉委員会");
            $table->string('role_16', 2)->nullable()->comment("役割（委員会等）-「精神保健福祉士業務指針」委員会（～2021）");
            $table->string('role_17', 2)->nullable()->comment("役割（委員会等）-東日本大震災復興支援委員会（～2021）");
            $table->string('role_18', 2)->nullable()->comment("役割（委員会等）-精神保健医療福祉ビジョン策定委員会（～2021）");
            $table->string('role_19', 2)->nullable()->comment("役割（委員会等）-「精神保健福祉士の倫理綱領」改訂検討委員会");
            $table->string('role_20', 2)->nullable()->comment("役割（委員会等）-メディア連携委員会");
            $table->string('role_21', 2)->nullable()->comment("役割（委員会等）-業務調査検討委員会");
            $table->string('role_22', 2)->nullable()->comment("役割（委員会等）-苦情処理規程改正等特別委員会");
            $table->string('role_23', 2)->nullable()->comment("役割（委員会等）-依存症及び関連問題対策委員会");
            $table->string('role_24', 2)->nullable()->comment("役割（委員会等）-子ども・若者・家族支援委員会");
            $table->string('role_25', 2)->nullable()->comment("役割（委員会等）-クローバー運営委員会");
            $table->string('role_26', 2)->nullable()->comment("役割（委員会等）-研修企画運営委員会");
            $table->string('role_27', 2)->nullable()->comment("役割（委員会等）-精神保健福祉士の資質向上検討委員会（～2021）");
            $table->string('role_28', 2)->nullable()->comment("役割（委員会等）-認定スーパーバイザー養成委員会");
            $table->string('role_29', 2)->nullable()->comment("役割（委員会等）-認定制度推進委員会");
            $table->string('role_30', 2)->nullable()->comment("役割（委員会等）-倫理委員会");
            $table->string('role_31', 2)->nullable()->comment("役割（委員会等）-役員選挙管理委員会（2022～）");
            $table->string('role_32', 2)->nullable()->comment("役割（委員会等）-代議員選挙管理委員会（2022～）");
            $table->string('role_33', 2)->nullable()->comment("役割（委員会等）-学会誌投稿論文等査読小委員会");
            $table->string('role_34', 2)->nullable()->comment("役割（委員会等）-分野別　スクールソーシャルワーク");
            $table->string('role_35', 2)->nullable()->comment("役割（委員会等）-分野別　認知症");
            $table->string('role_36', 2)->nullable()->comment("役割（委員会等）-分野別　産業精神保健");
            $table->string('role_37', 2)->nullable()->comment("役割（委員会等）-分野別　発達障害");
            $table->string('role_38', 2)->nullable()->comment("役割（委員会等）-分野別　メディア（～2019）");
            $table->string('role_39', 2)->nullable()->comment("役割（委員会等）-分野別　診療報酬");
            $table->string('role_40', 2)->nullable()->comment("役割（委員会等）-分野別　貧困問題");
            $table->string('role_41', 2)->nullable()->comment("役割（委員会等）-分野別　多文化共生ソーシャルワーク");
            $table->string('role_42', 2)->nullable()->comment("役割（委員会等）-災害対策委員");
            $table->string('role_43', 2)->nullable()->comment("役割（事業関係等）-55全国大会・18学術集会（愛知県）運営委員会");
            $table->string('role_44', 2)->nullable()->comment("役割（事業関係等）-18学術集会（愛知県）査読小委員会");
            $table->string('role_45', 2)->nullable()->comment("役割（事業関係等）-18学術集会（愛知県）分科会座長");
            $table->string('role_46', 2)->nullable()->comment("役割（事業関係等）-56全国大会・19学術集会（北海道）運営委員会");
            $table->string('role_47', 2)->nullable()->comment("役割（事業関係等）-19学術集会（北海道）査読小委員会");
            $table->string('role_48', 2)->nullable()->comment("役割（事業関係等）-19学術集会（北海道）分科会座長");
            $table->string('role_49', 2)->nullable()->comment("役割（事業関係等）-第7回定時総会運営委員");
            $table->string('role_50', 2)->nullable()->comment("役割（事業関係等）-R2総合福祉推進事業　事業担当者");
            $table->string('role_51', 2)->nullable()->comment("役割（事業関係等）-R2総合福祉推進事業　企画検討会議");
            $table->string('role_52', 2)->nullable()->comment("役割（事業関係等）-2019丸紅助成プロジェクトチーム");
            $table->string('attribute_1', 2)->nullable()->comment("属性ページ区分-理事");
            $table->string('attribute_2', 2)->nullable()->comment("属性ページ区分-クローバー登録者");
            $table->string('attribute_3', 2)->nullable()->comment("属性ページ区分-支部個人情報取扱者");
            $table->string('attribute_4', 2)->nullable()->comment("属性ページ区分-災害対策委員");
            $table->string('attribute_5', 2)->nullable()->comment("属性ページ区分-属性C");
            $table->string('attribute_6', 2)->nullable()->comment("属性ページ区分-属性D");
            $table->string('attribute_7', 2)->nullable()->comment("属性ページ区分-属性E");
            $table->string('attribute_8', 2)->nullable()->comment("属性ページ区分-属性F");
            $table->string('mypage_contact_section_1', 100)->nullable()->comment("マイページ連絡欄（重要）");
            $table->string('mypage_contact_section_2', 100)->nullable()->comment("マイページ連絡欄（通常）");
            $table->string('newsletter', 5)->nullable()->comment("メルマガ登録");
            $table->string('home_postal_code', 10)->nullable()->comment("自宅〒");
            $table->string('home_prefecture', 6)->nullable()->comment("自宅都道府県");
            $table->string('home_cities', 100)->nullable()->comment("自宅市区町村");
            $table->string('home_address', 100)->nullable()->comment("自宅番地");
            $table->string('home_name', 100)->nullable()->comment("自宅建物名");
            $table->string('home_telphone_number', 20)->nullable()->comment("自宅TEL");
            $table->string('home_fax_number', 20)->nullable()->comment("自宅FAX");
            $table->string('mobile', 13)->nullable()->comment("携帯電話");
            $table->string('office_availability', 3)->nullable()->comment("ご勤務先の有無について");
            $table->string('office_name', 100)->nullable()->comment("勤務先機関名");
            $table->string('office_postal_code', 10)->nullable()->comment("勤務先〒");
            $table->string('office_prefecture', 6)->nullable()->comment("勤務先都道府県");
            $table->string('office_cities', 100)->nullable()->comment("勤務先市区町村");
            $table->string('office_address', 100)->nullable()->comment("勤務先番地");
            $table->string('call_to_acceptable', 2)->nullable()->comment("勤務先への電話可否");
            $table->string('office_telephone_number', 20)->nullable()->comment("勤務先TEL");
            $table->string('office_extension_number', 20)->nullable()->comment("勤務先内線");
            $table->string('office_fax_number', 20)->nullable()->comment("勤務先FAX");
            $table->string('employer_type_1', 100)->nullable()->comment("勤務先種別1");
            $table->string('work_type_1', 100)->nullable()->comment("従事職種1");
            $table->string('position', 100)->nullable()->comment("勤務先立場");
            $table->string('management_entity', 100)->nullable()->comment("経営主体");
            $table->string('employment', 100)->nullable()->comment("雇用形態");
            $table->string('employer_type_2', 100)->nullable()->comment("勤務先種別2");
            $table->string('work_type_2', 100)->nullable()->comment("従事職種2");
            $table->string('employer_type_3', 100)->nullable()->comment("勤務先種別3");
            $table->string('work_type_3', 100)->nullable()->comment("従事職種3");
            $table->string('employer_type_4', 100)->nullable()->comment("勤務先種別4");
            $table->string('work_type_4', 100)->nullable()->comment("従事職種4");
            $table->string('last_academic_background', 100)->nullable()->comment("最終学歴");
            $table->string('examination_route', 100)->nullable()->comment("受験ルート");
            $table->string('school_name', 100)->nullable()->comment("学校名");
            $table->string('graduation_date', 10)->nullable()->comment("卒業年月");
            $table->string('social_worker_certification', 3)->nullable()->comment("社会福祉士資格の有無");
            $table->string('sicial_worker_obtain_annual', 10)->nullable()->comment("社会福祉士取得年度");
            $table->string('qualifications_licenses_1', 2)->nullable()->comment("所持資格・免許について-01_介護福祉士");
            $table->string('qualifications_licenses_2', 2)->nullable()->comment("所持資格・免許について-02_保健師");
            $table->string('qualifications_licenses_3', 2)->nullable()->comment("所持資格・免許について-03_看護師・准看護師");
            $table->string('qualifications_licenses_4', 2)->nullable()->comment("所持資格・免許について-04_公認心理師");
            $table->string('qualifications_licenses_5', 2)->nullable()->comment("所持資格・免許について-05_作業療法士");
            $table->string('qualifications_licenses_6', 2)->nullable()->comment("所持資格・免許について-06_理学療法士");
            $table->string('qualifications_licenses_7', 2)->nullable()->comment("所持資格・免許について-07_言語聴覚士");
            $table->string('qualifications_licenses_8', 2)->nullable()->comment("所持資格・免許について-08_医師・歯科医師");
            $table->string('qualifications_licenses_10', 2)->nullable()->comment("所持資格・免許について-10_幼・小・中・高教諭");
            $table->string('qualifications_licenses_11', 2)->nullable()->comment("所持資格・免許について-11_特別支援学校教員");
            $table->string('qualifications_licenses_12', 2)->nullable()->comment("所持資格・免許について-12_栄養士");
            $table->string('qualifications_licenses_13', 2)->nullable()->comment("所持資格・免許について-13_保育士");
            $table->string('qualifications_licenses_14', 2)->nullable()->comment("所持資格・免許について-14_児童自立支援専門員");
            $table->string('qualifications_licenses_15', 2)->nullable()->comment("所持資格・免許について-15_手話通訳士");
            $table->string('qualifications_licenses_16', 2)->nullable()->comment("所持資格・免許について-16_弁護士");
            $table->string('qualifications_licenses_17', 2)->nullable()->comment("所持資格・免許について-17_司法書士");
            $table->string('qualifications_licenses_18', 2)->nullable()->comment("所持資格・免許について-18_行政書士");
            $table->string('qualifications_licenses_19', 2)->nullable()->comment("所持資格・免許について-19_社会保険労務士");
            $table->string('qualifications_licenses_20', 2)->nullable()->comment("所持資格・免許について-20_介護支援専門員");
            $table->string('qualifications_licenses_21', 2)->nullable()->comment("所持資格・免許について-21_相談支援専門員");
            $table->string('qualifications_licenses_22', 2)->nullable()->comment("所持資格・免許について-22_サービス管理責任者");
            $table->string('certified_svr_registration', 2)->nullable()->comment("認定SVR登録-登録あり");
            $table->string('certified_svr_registration_no', 20)->nullable()->comment("認定SVR登録No");
            $table->string('clover_registration', 2)->nullable()->comment("クローバー登録-登録あり");
            $table->string('clover_registration_year', 10)->nullable()->comment("クローバー登録年度");
            $table->string('prefectural_associations_status', 100)->nullable()->comment("都道府県協会等への入会状況");
            $table->string('prefectural_associatio_1', 2)->nullable()->comment("入会している都道府県協会-北海道");
            $table->string('prefectural_associatio_2', 2)->nullable()->comment("入会している都道府県協会-青森県");
            $table->string('prefectural_associatio_3', 2)->nullable()->comment("入会している都道府県協会-岩手県");
            $table->string('prefectural_associatio_4', 2)->nullable()->comment("入会している都道府県協会-宮城県");
            $table->string('prefectural_associatio_5', 2)->nullable()->comment("入会している都道府県協会-秋田県");
            $table->string('prefectural_associatio_6', 2)->nullable()->comment("入会している都道府県協会-山形県");
            $table->string('prefectural_associatio_7', 2)->nullable()->comment("入会している都道府県協会-福島県");
            $table->string('prefectural_associatio_8', 2)->nullable()->comment("入会している都道府県協会-茨城県");
            $table->string('prefectural_associatio_9', 2)->nullable()->comment("入会している都道府県協会-栃木県");
            $table->string('prefectural_associatio_10', 2)->nullable()->comment("入会している都道府県協会-群馬県");
            $table->string('prefectural_associatio_11', 2)->nullable()->comment("入会している都道府県協会-埼玉県");
            $table->string('prefectural_associatio_12', 2)->nullable()->comment("入会している都道府県協会-千葉県");
            $table->string('prefectural_associatio_13', 2)->nullable()->comment("入会している都道府県協会-東京都");
            $table->string('prefectural_associatio_14', 2)->nullable()->comment("入会している都道府県協会-神奈川県");
            $table->string('prefectural_associatio_15', 2)->nullable()->comment("入会している都道府県協会-新潟県");
            $table->string('prefectural_associatio_16', 2)->nullable()->comment("入会している都道府県協会-富山県");
            $table->string('prefectural_associatio_17', 2)->nullable()->comment("入会している都道府県協会-石川県");
            $table->string('prefectural_associatio_18', 2)->nullable()->comment("入会している都道府県協会-福井県");
            $table->string('prefectural_associatio_19', 2)->nullable()->comment("入会している都道府県協会-山梨県");
            $table->string('prefectural_associatio_20', 2)->nullable()->comment("入会している都道府県協会-長野県");
            $table->string('prefectural_associatio_21', 2)->nullable()->comment("入会している都道府県協会-岐阜県");
            $table->string('prefectural_associatio_22', 2)->nullable()->comment("入会している都道府県協会-静岡県");
            $table->string('prefectural_associatio_23', 2)->nullable()->comment("入会している都道府県協会-愛知県");
            $table->string('prefectural_associatio_24', 2)->nullable()->comment("入会している都道府県協会-三重県");
            $table->string('prefectural_associatio_25', 2)->nullable()->comment("入会している都道府県協会-滋賀県");
            $table->string('prefectural_associatio_26', 2)->nullable()->comment("入会している都道府県協会-京都府");
            $table->string('prefectural_associatio_27', 2)->nullable()->comment("入会している都道府県協会-大阪府");
            $table->string('prefectural_associatio_28', 2)->nullable()->comment("入会している都道府県協会-兵庫県");
            $table->string('prefectural_associatio_29', 2)->nullable()->comment("入会している都道府県協会-奈良県");
            $table->string('prefectural_associatio_30', 2)->nullable()->comment("入会している都道府県協会-和歌山県");
            $table->string('prefectural_associatio_31', 2)->nullable()->comment("入会している都道府県協会-鳥取県");
            $table->string('prefectural_associatio_32', 2)->nullable()->comment("入会している都道府県協会-島根県");
            $table->string('prefectural_associatio_33', 2)->nullable()->comment("入会している都道府県協会-岡山県");
            $table->string('prefectural_associatio_34', 2)->nullable()->comment("入会している都道府県協会-広島県");
            $table->string('prefectural_associatio_35', 2)->nullable()->comment("入会している都道府県協会-山口県");
            $table->string('prefectural_associatio_36', 2)->nullable()->comment("入会している都道府県協会-徳島県");
            $table->string('prefectural_associatio_37', 2)->nullable()->comment("入会している都道府県協会-香川県");
            $table->string('prefectural_associatio_38', 2)->nullable()->comment("入会している都道府県協会-愛媛県");
            $table->string('prefectural_associatio_39', 2)->nullable()->comment("入会している都道府県協会-高知県");
            $table->string('prefectural_associatio_40', 2)->nullable()->comment("入会している都道府県協会-福岡県");
            $table->string('prefectural_associatio_41', 2)->nullable()->comment("入会している都道府県協会-佐賀県");
            $table->string('prefectural_associatio_42', 2)->nullable()->comment("入会している都道府県協会-長崎県");
            $table->string('prefectural_associatio_43', 2)->nullable()->comment("入会している都道府県協会-熊本県");
            $table->string('prefectural_associatio_44', 2)->nullable()->comment("入会している都道府県協会-大分県");
            $table->string('prefectural_associatio_45', 2)->nullable()->comment("入会している都道府県協会-宮崎県");
            $table->string('prefectural_associatio_46', 2)->nullable()->comment("入会している都道府県協会-鹿児島県");
            $table->string('prefectural_associatio_47', 2)->nullable()->comment("入会している都道府県協会-沖縄県");
            $table->string('core_training_status', 100)->nullable()->comment("基幹研修修了状況");
            $table->string('core_training_year', 10)->nullable()->comment("基幹研修修了年度");
            $table->string('certification_year', 10)->nullable()->comment("認定年度");
            $table->string('certification_number', 100)->nullable()->comment("認定番号");
            $table->string('training_accreditation_certification_status', 100)->nullable()->comment("研修認定・認定状況");
            $table->string('training_accreditation_certification_year', 10)->nullable()->comment("更新研修受講予定年度");
            $table->string('renewal_training_course_extension_status', 100)->nullable()->comment("更新研修受講延長状況");
            $table->string('renewal_training_course_extension_year', 10)->nullable()->comment("更新研修受講延長年度");
            $table->string('purchase_of_training_textbooks_1', 100)->nullable()->comment("研修テキスト購入状況-共通テキスト第１版");
            $table->string('purchase_of_training_textbooks_2', 100)->nullable()->comment("研修テキスト購入状況-共通テキスト第２版");
            $table->string('purchase_of_training_textbooks_3', 100)->nullable()->comment("研修テキスト購入状況-共通テキスト改訂第２版");
            $table->text('reason')->nullable()->comment("テキスト所持理由");
            $table->string('training_individual_form', 100)->nullable()->comment("研修個人票");
            $table->string('authorized_individual_form', 100)->nullable()->comment("認定個人票");
            $table->string('approval_date', 10)->nullable()->comment("入会承認日");
            $table->text('office_management_memo_1')->nullable()->comment("事務管理メモ-★★倫理委員会関連注意あり★★");
            $table->text('office_management_memo_2')->nullable()->comment("事務管理メモ-合格証入会（登録証未確認）");
            $table->text('office_management_memo_3')->nullable()->comment("事務管理メモ-便宜的職場なし");
            $table->text('office_management_memo_4')->nullable()->comment("事務管理メモ-（旧）領収書希望（氏名のみ）");
            $table->text('office_management_memo_5')->nullable()->comment("事務管理メモ-（旧）領収書希望（勤務先機関＋氏名）");
            $table->text('office_management_memo_6')->nullable()->comment("事務管理メモ-（旧）領収書：職場とりまとめ希望あり");
            $table->text('office_management_memo_7')->nullable()->comment("事務管理メモ-（旧）その他希望あり");
            $table->text('office_management_memo_8')->nullable()->comment("事務管理メモ-【重要】翌々年度まで前受会費あり");
            $table->text('office_management_memo_9')->nullable()->comment("事務管理メモ-【重要】入会時送金が分割となっている");
            $table->text('reasonable_accommodation')->nullable()->comment("合理的配慮");
            $table->string('absence_year', 10)->nullable()->comment("休会開始年度");
            $table->string('scheduled_reinstatement_year', 10)->nullable()->comment("復会予定年度");
            $table->string('reinstatement_year', 10)->nullable()->comment("復会年度");
            $table->string('withdrawal_date', 10)->nullable()->comment("退会処理日");
            $table->string('branch_general_meeting', 100)->nullable()->comment("2023年度支部総会");
            $table->text('free_text_1')->nullable()->comment("自由文字１");
            $table->text('free_text_2')->nullable()->comment("自由文字２");
            $table->text('free_text_3')->nullable()->comment("自由数値３");
            $table->text('clover_individual_important_contact_column')->nullable()->comment("クローバー個別重要連絡欄");
            $table->string('continuing_training_attendance_cycle', 100)->nullable()->comment("継続研修受講サイクル");
            $table->string('group_training_participation', 100)->nullable()->comment("集合研修受講状況");
            $table->string('need_attend_group_training_within_cycle', 100)->nullable()->comment("周期内の集合研修受講の必要性");
            $table->string('how_pay_registration_fee', 100)->nullable()->comment("登録費の納入方法");
            $table->string('clover_registration_fee_paid', 100)->nullable()->comment("2023年度クローバー登録費納入状況");
            $table->string('partner_registration', 100)->nullable()->comment("ぱあとなあ登録");
            $table->string('intention_accept_appointment', 100)->nullable()->comment("受任の意思");
            $table->string('clover_home_email', 100)->nullable()->comment("クローバー　自宅メールアドレス");
            $table->string('home_mailing_list_registration', 100)->nullable()->comment("自宅アドレス　メーリングリスト登録");
            $table->string('clover_affiliated_address', 100)->nullable()->comment("クローバー　所属アドレス");
            $table->string('clover_affiliated_mail_status', 100)->nullable()->comment("クローバー所属メール状況");
            $table->string('clover_mailing_list_registration', 100)->nullable()->comment("所属アドレス　メーリングリスト登録");
            $table->string('clover_mail_etc', 100)->nullable()->comment("クローバー　メールその他");
            $table->string('etc_mailing_list_registration', 100)->nullable()->comment("その他アドレス　メーリングリスト登録");
            $table->string('clover_family_1', 100)->nullable()->comment("クローバー登録希望家裁1");
            $table->string('clover_family_2', 100)->nullable()->comment("クローバー登録希望家裁2");
            $table->string('clover_family_3', 100)->nullable()->comment("クローバー登録希望家裁3");
            $table->string('clover_family_4', 100)->nullable()->comment("クローバー登録希望家裁4");
            $table->string('clover_family_5', 100)->nullable()->comment("クローバー登録希望家裁5");
            $table->string('clover_family_6', 100)->nullable()->comment("クローバー登録希望家裁6");
            $table->string('clover_family_7', 100)->nullable()->comment("クローバー登録希望家裁7");
            $table->string('clover_family_8', 100)->nullable()->comment("クローバー登録希望家裁8");
            $table->dateTime('registration_date')->nullable()->comment("登録日");
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('users_add_info');
    }
}
